### ISSUE TITLE
macOS環境における動作確認 / ver 1.000

### ISSUE THREAD

**Issue by KaiseiYokoyama** [negset/Firple#1]
## 環境
macOS Big Sur 11.4
Visual Studio Code 1.58.2
Firple v1.000 https://github.com/negset/Firple/releases/tag/1.000

## 検証項目
- [x] 半角と全角が1:2になってるか
- [x] リガチャが使えるか
- [x] レンダリングが汚い等の問題がないか

**Comment by KaiseiYokoyama** [comment]
半角と全角の横幅の比率はうまくいってそう

<img width="434" alt="スクリーンショット 2021-07-31 11 20 39" src="https://user-images.githubusercontent.com/8509057/127725842-2d005f82-02c2-4267-9290-2df329413c7a.png">

**Comment by KaiseiYokoyama** [comment]
リガチャされてないかも

- `->`
<img width="614" alt="スクリーンショット 2021-07-31 11 23 45" src="https://user-images.githubusercontent.com/8509057/127725910-28ee481d-5635-4bd0-8613-904d4d4eab7a.png">

- `=>`
<img width="440" alt="スクリーンショット 2021-07-31 11 24 29" src="https://user-images.githubusercontent.com/8509057/127725930-6fea61ad-957a-4692-b072-2534410c13c8.png">

**Comment by KaiseiYokoyama** [comment]
ざっと見た感じレンダリングに変なところはないかな

**Comment by negset** [comment]
VSCode側でリガチャの機能は有効化されてる？

横幅比は以下のようなのがよりわかりやすいです
```
|Sunday|Monday|Tuesday|
|:-----|:-----|:------|
|日曜日|月曜日|火曜日 |
```

**Comment by KaiseiYokoyama** [comment]
横幅再確認
<img width="221" alt="スクリーンショット 2021-07-31 12 53 23" src="https://user-images.githubusercontent.com/8509057/127727923-7cb706b6-4e53-4d3d-8caf-9a79c645a190.png">

**Comment by KaiseiYokoyama** [comment]
VSCodeの設定でligature無効になってたので直しました

リガチャも上手く動いてそう 👍 

- `->`
<img width="615" alt="スクリーンショット 2021-07-31 12 55 36" src="https://user-images.githubusercontent.com/8509057/127727961-30312c2c-1063-437e-942c-feb4797d1fc9.png">

- `>=`, `=>`
<img width="450" alt="スクリーンショット 2021-07-31 12 57 25" src="https://user-images.githubusercontent.com/8509057/127727993-4d0a2c6c-ee4e-474d-8c6b-603a3b8af68d.png">

**Comment by negset** [comment]
検証助かりました:pray:
