### ISSUE TITLE
提案：全角空白の可視化

### ISSUE THREAD

**Issue by u7f8au7fbd** [negset/Firple#5]
# 概要
 日本語向けのコーディング環境において、全角空白の混入が原因で意図しない動作やトラブルが発生することがあります。特に、全角空白が視覚的に他のスペースと見分けがつきにくい場合が多く、これが問題となるケースが増えています。

# 要望内容
 全角空白を他の文字や半角スペースと区別できるように、以下のような可視化機能を追加していただけると大変助かります：
- 全角空白を特殊な記号や目立つ色で表示する。
- 設定でこの可視化機能をオン/オフできるようにする。

# 利点
- 全角空白が混入した際にすぐに気づき、デバッグやトラブルシューティングの手間を削減できる。
- 特に多国語対応のプロジェクトやチームでのコーディングにおいて、コミュニケーションミスや誤解を減らすことができる。

# 結論
この機能により、日本語でのコーディング効率が向上し、特にコードレビューやメンテナンス作業における無駄な手間を削減できると期待しています。ご検討いただけますと幸いです。

**Comment by negset** [comment]
提案ありがとうございます。

私個人の考えとしては、スペース可視化はエディタ側で行うべきだと考えています。
実際、いくつかの IDE において、コード中の全角スペースに下線を引いて示してくれる機能があります。

しかし、スペース可視化に需要があることも認識しましたので、対応を考えたいと思います。

> 設定でこの可視化機能をオン/オフできるようにする。

フォントの機能で切り替え可能にする、となると実装が難しいかもしれないです。
一方で、フォント生成時にオン/オフを指定できるようにする方法は、容易に実装出来そうです。

まずは後者の方針で進めたいと思います。

**Comment by u7f8au7fbd** [comment]
ご対応返信ありがとうございます。
IDE機能としての考え，おっしゃる通りであります．
後者の機能の対応検討ありがとうございます。

**Comment by negset** [comment]
[5.000](https://github.com/negset/Firple/releases/tag/5.000) で全角スペース可視化に対応しました。
良ければ試してみてください。

フォント機能 (OpenType features) で切り替え可能にする実装が上手くいったので、標準は OFF でエディタ側で `cv33` を有効にすることで可視化される形にしました。
各種エディタにおける切り替え方法は [FiraCode のドキュメント](https://github.com/tonsky/FiraCode/wiki/How-to-enable-stylistic-sets) を参照してください。

また OpenType features に対応しないエディタを考慮して、生成時にオプションを与えることで標準で ON にできるようにしました。
```sh
$ ./firple.py --freeze-features cv33
```

ご意見などあれば是非教えてください。

**Comment by u7f8au7fbd** [comment]
機能の確認いたしました．
ご対応のほど本当にありがとうございました．
今後これらが私のメインフォントになりそうです．
